### ISSUE TITLE
program version added to vcf headers is incorrect

### ISSUE THREAD

**Issue by charlesgregory** [blachlylab/recontig#18]
@jblachly Do you know a good way to pull the version from the git commit/tag and have it automatically compiled in as an `enum` so I don't have to update it manually? I think htslib does this?
https://github.com/blachlylab/recontig/blob/2962b755d5c627c95e8d875583a1fb5c14a374de/source/recontig/vcf.d#L76

**Comment by jblachly** [comment]
Well keep in mind HEAD may not be at a tag.

Many repos will use `git-rev-parse`:

```
jsbmbp13:/tmp/recontig$ git rev-parse HEAD
2962b755d5c627c95e8d875583a1fb5c14a374de
jsbmbp13:/tmp/recontig$ git rev-parse --short HEAD
2962b75
```

If you are sure there is a tag you can use `git-describe`:

```
jsbmbp13:/tmp/recontig$ git describe --tags
v1.2.0
```

So, easy answer would be to have a dub `prebuildcommand` that dumped output of one of those to a file, and either `import` it directly with a mixin, or otherwise postprocess the file to be a valid D module that can be imported.

I am fairly certain I did this in one of our tools but can't remember which one
